### ISSUE TITLE
To-do: documentation

### ISSUE THREAD

**Issue by benbender** [benbender/x1c6-hackintosh#10]
- [ ] SSDT-TB: Document the thunderbolt approach and findings in this repo (background, requirements, bios-settings, state, caveats, etc)
- [ ] HowTo Debugging. This should cover: How to check for ACPI-errors? How to patch SSDTs? How to redirect native ACPI-Debug? How to print from ACPI to syslog? Msgbuf and how it can be patched? Tips & tricks
- [ ] Add a changelog to README.md
- [ ] Add revisions + changelogs to every major SSDT
